In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/phishing_email.csv")
df.head()

                                       text_combined  label
0  hpl nom may 25 2001 see attached file hplno 52...      0
1  nom actual vols 24 th forwarded sabrae zajac h...      0
2  enron actuals march 30 april 1 201 estimated a...      0
3  hpl nom may 30 2001 see attached file hplno 53...      0
4  hpl nom june 1 2001 see attached file hplno 60...      0

In [2]:
print(df.shape)
print(df.columns)

(82486, 2)
Index(['text_combined', 'label'], dtype='str')

In [3]:
df[label].value_counts()

NameError: name 'label' is not defined

In [4]:
df['label'].value_counts()

label
1    42891
0    39595
Name: count, dtype: int64

In [ ]:
df.isnull().sum()
## missing values in the dataset, there are no missing values in the dataset.

text_combined    0
label            0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(408)

In [ ]:
df.duplicated(subset='text_combined').sum()
## Duplicates 408 duplicate rows (~0.5%). Same count when comparing text only,so no conflicting labels. Will remove before training to avoid data leakage.

np.int64(408)

In [9]:
df[df["label"] == 1]

                                           text_combined  label
3503   link dwl g 510 802 11 g wireless pci lan adapt...      1
3504   indemand payperview movies sports wed 15 sep 2...      1
3505   want lose 19 weight try adipren hello special ...      1
3506   cialis xanax valium viagra low price prescript...      1
3507   pre order see image click indelible backscatte...      1
...                                                  ...    ...
82481  info advantageapartmentscom infoadvantageapart...      1
82482  monkeyorg helpdeskmonkeyorg monkeyorg hi josep...      1
82483  help center infohelpcentercoza_infohelpcenterc...      1
82484  metamask infosofamekarcom verify metamask wall...      1
82485  fastway infofastwaycoza_infofastwaycoza_infofa...      1

[42891 rows x 2 columns]

In [10]:
print(df[df["label"] == 1]["text_combined"].iloc[0])

link dwl g 510 802 11 g wireless pci lan adapter 39 85 39 85 dwl g 510 high speed 2 4 ghz 802 11 g wireless pci lan adapter ieee 802 11 g standardupto 54 mbpsoperating frequency range 2 4 ghz ideal solution enabling wireless networking capabilities desktops pcs home office dwl g 510 visit http www computron com deals link dwl g 510 802 11 g wireless pci lan adapter link g 510 wireless pci adapter featuring latest ieee 802 11 g wireless technology deliverincredibly fast data transfer 2 4 ghz frequency g 510 features 802 11 g standard backwards compatible existing 802 11 11 b products already also offers 64 128 bit wep encryption includes removable antenna driver cd get link g 510 wireless pci lan adapter today general features pci interface removable antenna 64 128 bit wep encryption link act led plug play one stop distributorjebel ali duty free zonedubai uae www computron com latest clearance sale listing contact sales department limited quantities available selected specials details please send enquiries dealers emirates net aeor contact via www computron com compaq hewlett packard 3 com dell intel iomega epson aopen creative toshiba apc cisco us robotics microsoft canon intellinet targus viewsonic ibm sony lots complaints suggestions contact customerservice computron com tel 971 4 8834464 prices u dollars ex works fax 971 4 8834454 jebel ali duty free zone www computron com prices availability subject change usa canada u e without notice receive special offers plain text format reply mail request export email considered spam long include contact information remove instructions message intended dealer resellers somehow gotten list error reason would like removed please reply remove subject line message message sent compliance federal legislation commercial e mail h r 4176 section 101 paragraph e 1 bill 1618 title iii passed 105 th u congress logos trademarks property respective owners products may exactly shown unsubscribe computron 6 follow link click link copy paste address browser

In [11]:
import textwrap

email = df[df["label"] == 1]["text_combined"].iloc[0]
print(textwrap.fill(email, 100))

link dwl g 510 802 11 g wireless pci lan adapter 39 85 39 85 dwl g 510 high speed 2 4 ghz 802 11 g
wireless pci lan adapter ieee 802 11 g standardupto 54 mbpsoperating frequency range 2 4 ghz ideal
solution enabling wireless networking capabilities desktops pcs home office dwl g 510 visit http www
computron com deals link dwl g 510 802 11 g wireless pci lan adapter link g 510 wireless pci adapter
featuring latest ieee 802 11 g wireless technology deliverincredibly fast data transfer 2 4 ghz
frequency g 510 features 802 11 g standard backwards compatible existing 802 11 11 b products
already also offers 64 128 bit wep encryption includes removable antenna driver cd get link g 510
wireless pci lan adapter today general features pci interface removable antenna 64 128 bit wep
encryption link act led plug play one stop distributorjebel ali duty free zonedubai uae www
computron com latest clearance sale listing contact sales department limited quantities available
selected specials details please send enquiries dealers emirates net aeor contact via www computron
com compaq hewlett packard 3 com dell intel iomega epson aopen creative toshiba apc cisco us
robotics microsoft canon intellinet targus viewsonic ibm sony lots complaints suggestions contact
customerservice computron com tel 971 4 8834464 prices u dollars ex works fax 971 4 8834454 jebel
ali duty free zone www computron com prices availability subject change usa canada u e without
notice receive special offers plain text format reply mail request export email considered spam long
include contact information remove instructions message intended dealer resellers somehow gotten
list error reason would like removed please reply remove subject line message message sent
compliance federal legislation commercial e mail h r 4176 section 101 paragraph e 1 bill 1618 title
iii passed 105 th u congress logos trademarks property respective owners products may exactly shown
unsubscribe computron 6 follow link click link copy paste address browser

In [12]:
email = df[df["label"] == 1]["text_combined"].iloc[-1]
print(textwrap.fill(email, 100))

fastway infofastwaycoza_infofastwaycoza_infofastwaycoza154565em5269xfund02ml announcing jotform
tables spreadsheet isnt enough team shipment way dear client parcel number bn1018894701 way package
stopped post r2500 shipping cost paid shipping cost paid package returned continue fastway app see
current status package next step shipment way dear client parcel number bn1018894701 way package
stopped post r2500 shipping cost paid shipping cost paid package returned continue fastway app see
current status package next step announcing jotform tables spreadsheet isnt enough team shipment way
dear client parcel number bn1018894701 way package stopped post r2500 shipping cost paid shipping
cost paid package returned continue fastway app see current status package next step wed 21 dec 2022
013332 0000 utc shipment way

## Which label is phishing?
1 = phishing/spam, 0 = legitimate (confirmed by reading examples).
Label 1 includes both spam (product ads) and phishing (e.g. fake courier
asking for a shipping fee). Common phishing clues: impersonation,
urgency/threats, payment or credential requests, generic greetings.

## Cleaning

In [13]:
df_clean=df.drop_duplicates()
df_clean = df_clean.rename(columns={"text_combined": "text"})
print(df_clean.shape)
print(df_clean.columns)

(82078, 2)
Index(['text', 'label'], dtype='str')

In [15]:
df_clean.to_csv("../data/processed/emails_clean.csv", index=False)

In [16]:
check = pd.read_csv("../data/processed/emails_clean.csv")
print(check.shape)
print(check.columns)

(82078, 2)
Index(['text', 'label'], dtype='str')